#
# $Revision: 1.0 $
# $Date: 2013-03-21 11:21:26 $
# @author: David Rodenas-Herraiz <rodenasherraiz.david@gmail.com>
# ========================================================================
# 

COMPONENT=meshDeviceAppC
CFLAGS += -I$(shell pwd)/..

include ../../../Makefile.include
